install.packages("ggpubr")
install.packages("moments")
install.packages("corrplot")
install.packages("PerformanceAnalytics")
install.packages("gplots")
install.packages(c("factoextra", "dendextend"))

install.packages("labdsv")
install.packages("ggraph")
install.packages("igraph")
install.packages("tidyverse")
install.packages(RColorBrewer)
install.packages("ggplot2")
install.packages("data.table")
install.packages("dplyr")
install.packages("tidyr")
